MundialProg3/Controllers/PaisController.cs
using LogicaAplicacion.ICasoDeUso.IPais;
using LogicaAplicacion.ICasoDeUso.IRegion;
using LogicaDeNegocio.EntidadesNegocio;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MundialProg3.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace MundialProg3.Controllers
{
    public class PaisController : Controller
    {

        public IAltaPais AltaPais;
        public IEliminarPais EliminarPais;
        public IEditarPais EditarPais;
        public IMostrarPaises MostrarPaises;
        public IObtenerPorRegion ObtenerPorRegion;
        public IBuscarPaisPorAlfa3 BuscarPaisPorAlfa3;
        public IBuscarPaisPorID BuscarPaisPorID;
        public IMostrarRegiones MostrarRegiones;
        public IMostrarRegion MostrarRegion;
        public IWebHostEnvironment WebHostEnvironment;

        public PaisController(IAltaPais altaPais, IEliminarPais eliminarPais, IEditarPais editarPais, IMostrarPaises mostrarPaises, 
            IObtenerPorRegion obtenerPorRegion, IWebHostEnvironment webHost, IBuscarPaisPorAlfa3 buscarPaisPorAlfa3, IBuscarPaisPorID buscarPaisPorID,
            IMostrarRegiones mostrarRegiones, IMostrarRegion mostrarRegionPorId)
        {
            this.AltaPais = altaPais;
            this.EliminarPais = eliminarPais;
            this.EditarPais = editarPais;
            this.MostrarPaises = mostrarPaises;
            this.ObtenerPorRegion = obtenerPorRegion;
            this.BuscarPaisPorAlfa3 = buscarPaisPorAlfa3;
            this.BuscarPaisPorID = buscarPaisPorID;
            this.MostrarRegiones = mostrarRegiones;
            this.MostrarRegion = mostrarRegionPorId;
            this.WebHostEnvironment = webHost;
        }

        public IActionResult AgregarPais()
        {
            ViewModelPaises vmPais = new ViewModelPaises();
            vmPais.TodasLasRegiones = MostrarRegiones.FindAll();
            return View("AgregarPais", vmPais);
        }

        [HttpPost]
        public IActionResult AgregarPais(ViewModelPaises pais)
        {
            try
            {
                Pais miPais = new Pais();
                miPais.IsoAlfa3 = pais.IsoAlfa3.ToUpper(); 
                miPais.PbiPerCapita = pais.PbiPerCapita;
                miPais.Poblacion = pais.Poblacion;
                miPais.Nombre = pais.Nombre;
                miPais.Imagen = pais.ImagenBandera.FileName;
                miPais.IdRegion = pais.IdRegion;
                miPais.Region = MostrarRegion.FindById(pais.IdRegion);
                AltaPais.Add(miPais);

                string rutaRaiz = WebHostEnvironment.WebRootPath;
                string rutaImagenes = Path.Combine(rutaRaiz,"Imagenes");
                string rutaArchivo = Path.Combine(rutaImagenes, pais.ImagenBandera.FileName);
                FileStream streamFoto = new FileStream(rutaArchivo, FileMode.Create);
                pais.ImagenBandera.CopyTo(streamFoto);
                return RedirectToAction("ListarPaises");
            }
            catch (Exception ex)
            {
                pais.TodasLasRegiones = MostrarRegiones.FindAll();
                ViewBag.Error = ex.Message;
                return View("AgregarPais", pais);
            }
        }
        



        public IActionResult ListarPaises()
        {
            IEnumerable<Pais> paises = MostrarPaises.FindAll();
            return View(paises);
        }


        public IActionResult BajaPais(int idPais)
        {
            try
            {
                Pais pais = new Pais();
                pais = BuscarPaisPorID.FindByID(idPais);
                EliminarPais.Delete(pais);
            }
            catch (Exception ex)
            {
                if (ex.InnerException.Message.Contains("REFERENCE constraint"))
                {
                    ViewBag.Error = "No se puede eliminar debido a que tiene una selección asignada";
                }
                else
                {
                    ViewBag.Error = ex.Message;
                }
                Pais pais = BuscarPaisPorID.FindByID(idPais);
                return View("VerPais", pais);
            }

            return RedirectToAction("ListarPaises");
        }


        public IActionResult UpdatePais(int idPais)
        {
            ViewModelPaises vmPais = new ViewModelPaises();
            Pais pais = BuscarPaisPorID.FindByID(idPais);
            vmPais.IdPais = pais.Id;
            vmPais.IsoAlfa3 = pais.IsoAlfa3;
            vmPais.PbiPerCapita = pais.PbiPerCapita;
            vmPais.Poblacion = pais.Poblacion;
            vmPais.Nombre = pais.Nombre;
            vmPais.TodasLasRegiones = MostrarRegiones.FindAll();
            vmPais.IdRegion = pais.Region.Id;
            return View("UpdatePais", vmPais);
        }

        [HttpPost]
        public IActionResult UpdatePais(ViewModelPaises paisVM)
        {

            try
            {
                Pais pais = BuscarPaisPorID.FindByID(paisVM.IdPais);
                pais.IsoAlfa3 = paisVM.IsoAlfa3.ToUpper();
                pais.PbiPerCapita = paisVM.PbiPerCapita;
                pais.Poblacion = paisVM.Poblacion;
                pais.Nombre = paisVM.Nombre;
                if (paisVM.ImagenBandera != null) { 
                    pais.Imagen = paisVM.ImagenBandera.FileName;
                    string rutaRaiz = WebHostEnvironment.WebRootPath;
                    string rutaImagenes = Path.Combine(rutaRaiz, "Imagenes");
                    string rutaArchivo = Path.Combine(rutaImagenes, paisVM.ImagenBandera.FileName);
                    FileStream streamFoto = new FileStream(rutaArchivo, FileMode.Create);
                    paisVM.ImagenBandera.CopyTo(streamFoto);
                }
                if (paisVM.IdRegion != null & paisVM.IdRegion != 0)
                {
                    pais.Region = MostrarRegion.FindById(paisVM.IdRegion);

                }
                EditarPais.Update(pais);
            }
            catch (Exception ex)
            {
                paisVM.TodasLasRegiones = MostrarRegiones.FindAll();
                ViewBag.Error = ex.Message;
                return View("UpdatePais", paisVM);

            }

            return RedirectToAction("ListarPaises");

        }

        public IActionResult BuscarPorAlfa3()
        {
            return View("BuscarPorAlfa3");
        }

        
        public IActionResult BuscarPorIsoAlfa3(string codAlfa3)
        {

            try
            {           
                Pais pais = BuscarPaisPorAlfa3.BuscarPaisPorAlfa3(codAlfa3);
            
                
                return View("VerPais",pais);
                
                
            }
            catch (Exception ex)
            {

                if (ex.Message.Contains("Sequence contains no elements"))
                {
                    ViewBag.Error = "No se encontró un país por el código ISO ingresado";
                }
                else
                {
                    ViewBag.Error = ex.Message;
                }

                return View("BuscarPorAlfa3");

            }

        }
           
        


        public IActionResult BuscarPaisesPorRegion()
        {
            
            ViewModelPaises vmPais = new ViewModelPaises();
            vmPais.TodasLasRegiones = MostrarRegiones.FindAll();
            return View("BuscarPaisesPorRegion", vmPais);
        }

        [HttpPost]
        public IActionResult BuscarPaisesPorRegion(int idRegion)
        {
            try
            {
                Region region = MostrarRegion.FindById(idRegion);
                IEnumerable<Pais> paises = ObtenerPorRegion.ObtenerPaisesPorRegion(region);
                
                if (paises.Count() != 0)
                {
                    return View("VerPaisesPorRegion", paises);
                }
                else
                {
                    throw new Exception("No se encontraron países de la región seleccionada.");
                }
            }
            catch (Exception ex)
            {

                if (ex.Message.Contains("No se encontraron países de la región seleccionada."))
                {
                    ViewBag.Error = "No se encontraron países de la región seleccionada.";
                }
                else
                {
                    ViewBag.Error = ex.Message;
                }

                ViewModelPaises vmPais = new ViewModelPaises();
                vmPais.TodasLasRegiones = MostrarRegiones.FindAll();
                return View("BuscarPaisesPorRegion", vmPais);

            }

        }


        public IActionResult BuscarPaisPorId()
        {
            return View("BuscarPorId");
        }

        [HttpPost]
        public IActionResult BuscarPaisPorId(int id)
        {

            try
            {
                Pais pais = BuscarPaisPorID.FindByID(id);
                return View("VerPais", pais);
            }
            catch (Exception ex)
            {

                if (ex.Message.Contains("Sequence contains no elements"))
                {
                    ViewBag.Error = "No se encontró un país por el id ingresado";
                }
                else
                {
                    ViewBag.Error = ex.Message;
                }
                return View("BuscarPorId");

            }

        }
    }
}

MundialProg3/Controllers/UsuarioController.cs
using LogicaAplicacionUsuarios.ICRoles;
using LogicaAplicacionUsuarios.ICUsuarios;
using LogicaDeNegocioUsuarios;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MundialProg3.Models;
using System;
using System.Collections.Generic;

namespace MundialProg3.Controllers
{
    public class UsuarioController : Controller
    {

        public IAltaUsuario AltaUsuario;
        public IBuscarUsuarioPorNombre UsuarioPorNombre;
        public ILogin Login;
        public IFindAll FindAllRoles;
        public IFindById FindByIdRoles;
        public IAdd AgregarRol;

        public UsuarioController(IAltaUsuario altaUsuario, IBuscarUsuarioPorNombre usuarioPorNombre, ILogin login,
                                IFindAll findAllRoles, IFindById findByIdRoles, IAdd agregarRol)
        {
            this.AltaUsuario = altaUsuario;
            this.UsuarioPorNombre = usuarioPorNombre;
            this.Login = login;
            this.FindAllRoles = findAllRoles;
            this.FindByIdRoles = findByIdRoles;
            this.AgregarRol = agregarRol;
        }


        #region LOGIN
        public IActionResult InicioSesion()
        {
            ViewModelUsuarios vmRoles = new ViewModelUsuarios();
            vmRoles.TodosLosRoles = FindAllRoles.FindAll();

            return View("InicioSesion",vmRoles);
        }

        [HttpPost]
        public IActionResult IniciarSesion(string email, string password, int idRol)
        {
            try
            {
                Usuarios usu = new Usuarios();
                Roles rolBuscado = FindByIdRoles.FindById(idRol);

                if (idRol == 1 && Login.Login(email, password, idRol) != null) // 1 = rol admin
                {
                    usu = UsuarioPorNombre.BuscarUsuarioPorNombre(email);
                    HttpContext.Session.SetString("Rol", usu.MisRoles[0].Nombre);
                    return RedirectToAction("Index", "Home");

                }
                else if (idRol == 2 && Login.Login(email, password, idRol) != null) // 2 = rol apostador
                {
                    usu = UsuarioPorNombre.BuscarUsuarioPorNombre(email);
                    HttpContext.Session.SetString("Rol", rolBuscado.Nombre);
                    return RedirectToAction("Index", "Home");

                }
                else if (idRol == 3 && Login.Login(email, password, idRol) != null) // 3 = rol invitado
                {
                    usu = UsuarioPorNombre.BuscarUsuarioPorNombre(email);
                    HttpContext.Session.SetString("Rol", rolBuscado.Nombre);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return View("InicioSesion");
                }
            }
            catch (Exception ex)
            {

                return ViewBag.Error = ex.Message;
            }


        }
        #endregion


        #region AltaUsuario

        public IActionResult AgregarUsuario()
        {
            
            return View("AgregarUsuario");
        }

        [HttpPost]    
        public IActionResult CrearUsuario(Usuarios nuevoUsuario)
        {

            try
            {

                nuevoUsuario.MisRoles = new List<Roles>();
                Roles rol = FindByIdRoles.FindById(3); // 3 = rol de invitado
                nuevoUsuario.MisRoles.Add(rol);
                AltaUsuario.Add(nuevoUsuario);

                return RedirectToAction("InicioSesion");


            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return RedirectToAction("InicioSesion");
            }

           
        }



        #endregion


        #region LOGOUT
        public IActionResult CerrarSesion()
        {
            HttpContext.Session.Clear();

            return RedirectToAction("InicioSesion");
        }
        #endregion

    }
}

MundialProg3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MundialProg3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MundialProg3</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">


                        @*TODOS LOS USUARIOS*@
                        @if (Context.Session.GetString("Rol") == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="AgregarUsuario">Registro de Usuario</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="InicioSesion">Inicio de sesión</a>
                            </li> 
                        }
                          
                        
                        @*ADMIN*@
                        @if (Context.Session.GetString("Rol") != null && Context.Session.GetString("Rol").Equals("Admin"))
                        {
                            
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Pais" asp-action="AgregarPais">AltaPais</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Pais" asp-action="ListarPaises">ListarPaises</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Pais" asp-action="BuscarPorAlfa3">BuscarPorCodAlfa</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Pais" asp-action="BuscarPaisesPorRegion">Obtener países por región</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Pais" asp-action="BuscarPaisPorId">Buscar país por id</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="SeleccionWebApi" asp-action="CrearSeleccion">Añadir selección</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="SeleccionWebApi" asp-action="ListarSelecciones">Ver selecciones</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="SeleccionWebApi" asp-action="BuscarPorId">Buscar selección por id</a>
                            </li>
                          
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="PartidoWebApi" asp-action="BuscarPartidos">Filtrar partidos</a>
                            </li> 
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="PartidoWebApi" asp-action="BuscarTablaGrupo">Ver tabla de grupo</a>
                            </li> 
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="CerrarSesion">Cerrar sesión</a>
                            </li>
                          @*  <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="PartidoWebApi" asp-action="ListarPartidos">Ver todos los partidos</a>
                            </li>*@

                        }

                        @*APOSTADOR*@
                        @if (Context.Session.GetString("Rol") != null && Context.Session.GetString("Rol").Equals("Apostador"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="PartidoWebApi" asp-action="BuscarPartidos">Filtrar partidos</a>
                            </li> 
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="PartidoWebApi" asp-action="BuscarTablaGrupo">Ver tabla de grupo</a>
                            </li> 
                             <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="CerrarSesion">Cerrar sesión</a>
                            </li>
                        }

                        @*INVITADO*@
                        @if (Context.Session.GetString("Rol") != null && Context.Session.GetString("Rol").Equals("Invitado"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="SeleccionWebApi" asp-action="ListarSelecciones">Ver selecciones</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="SeleccionWebApi" asp-action="BuscarPorId">Buscar selección por id</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="CerrarSesion">Cerrar sesión</a>
                            </li>
                        }
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MundialProg3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>
@using Microsoft.AspNetCore.Http